spring:
  application:
    name: main-service
  profiles:
    active: main-service
  config:
    import: "configserver:"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/